// Generated by `wit-bindgen` 0.43.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod wavelet {
  pub mod meta {
    /// Code as a WIT type (design.md §6.2).
    ///
    /// Homoiconicity has to survive the component boundary, so "a form" is itself a
    /// WIT type. WIT has no recursive types, so a form tree is encoded as an arena:
    /// a flat node table plus a root index. This mirrors `src/form.rs`
    /// (`Arena`/`Node`/`NodeId`) exactly.
    ///
    /// A call is just a `tup` whose first element is the head — there is no separate
    /// `call` node, matching `form::Node` (which has no `Call` variant).
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod code {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type NodeId = u32;
      #[derive(Clone)]
      pub enum Node {
        BoolVal(bool),
        IntVal(i64),
        DecVal(f64),
        CharVal(char),
        StrVal(_rt::String),
        Sym(_rt::String),
        Qsym((_rt::String,_rt::String,)),
        /// (alias, name)
        Tup(_rt::Vec::<NodeId>),
        /// a call is a tup whose head is items[0]
        Lst(_rt::Vec::<NodeId>),
        Rec(_rt::Vec::<(_rt::String,NodeId,)>),
        Flg(_rt::Vec::<_rt::String>),
      }
      impl ::core::fmt::Debug for Node {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Node::BoolVal(e) => {
              f.debug_tuple("Node::BoolVal").field(e).finish()
            }
            Node::IntVal(e) => {
              f.debug_tuple("Node::IntVal").field(e).finish()
            }
            Node::DecVal(e) => {
              f.debug_tuple("Node::DecVal").field(e).finish()
            }
            Node::CharVal(e) => {
              f.debug_tuple("Node::CharVal").field(e).finish()
            }
            Node::StrVal(e) => {
              f.debug_tuple("Node::StrVal").field(e).finish()
            }
            Node::Sym(e) => {
              f.debug_tuple("Node::Sym").field(e).finish()
            }
            Node::Qsym(e) => {
              f.debug_tuple("Node::Qsym").field(e).finish()
            }
            Node::Tup(e) => {
              f.debug_tuple("Node::Tup").field(e).finish()
            }
            Node::Lst(e) => {
              f.debug_tuple("Node::Lst").field(e).finish()
            }
            Node::Rec(e) => {
              f.debug_tuple("Node::Rec").field(e).finish()
            }
            Node::Flg(e) => {
              f.debug_tuple("Node::Flg").field(e).finish()
            }
          }
        }
      }
      #[derive(Clone)]
      pub struct Tree {
        pub nodes: _rt::Vec::<Node>,
        pub root: NodeId,
        pub spans: _rt::Vec::<(u32,u32,)>,
      }
      impl ::core::fmt::Debug for Tree {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Tree").field("nodes", &self.nodes).field("root", &self.root).field("spans", &self.spans).finish()
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod wavelet {
    pub mod meta {
      /// Macros are components (design.md §6.3).
      ///
      /// A component exporting `wavelet:meta/macros` is a macro library. The compiler
      /// instantiates it at build time, calls `manifest` to learn each macro's
      /// `(name, arity)` (so the reader knows TitleCase arities across components),
      /// and routes expansion through `expand`: it marshals the call's argument forms
      /// into a `tree`, calls `expand(name, args)`, and lifts the returned `tree` back
      /// into the form arena. Macros are thus sandboxed by construction — a macro guest
      /// runs with no ambient capabilities.
      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod macros {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type Tree = super::super::super::super::wavelet::meta::code::Tree;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_manifest_cabi<T: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T::manifest()
        };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        let vec4 = result0;
        let len4 = vec4.len();
        let layout4 = _rt::alloc::Layout::from_size_align(vec4.len() * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result4, _cleanup4) = wit_bindgen::rt::Cleanup::new(layout4);if let Some(cleanup) = _cleanup4 { cleanup.forget(); }
        for (i, e) in vec4.into_iter().enumerate() {
          let base = result4.add(i * (3*::core::mem::size_of::<*const u8>()));
          {
            let (t2_0, t2_1, ) = e;
            let vec3 = (t2_0.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(t2_1);
          }
        }
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
        *ptr1.add(0).cast::<*mut u8>() = result4;
        ptr1
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_manifest<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base4 = l0;
        let len4 = l1;
        for i in 0..len4 {
          let base = base4.add(i * (3*::core::mem::size_of::<*const u8>()));
          {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l2, l3, 1);
          }
        }
        _rt::cabi_dealloc(base4, len4 * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_expand_cabi<T: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i32,arg5: *mut u8,arg6: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result42 = {
        let len0 = arg1;
        let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
        let base38 = arg2;
        let len38 = arg3;
        let mut result38 = _rt::Vec::with_capacity(len38);
        for i in 0..len38 {
          let base = base38.add(i * (8+4*::core::mem::size_of::<*const u8>()));
          let e38 = {
            let l1 = i32::from(*base.add(0).cast::<u8>());
            use super::super::super::super::wavelet::meta::code::Node as V37;
            let v37 = match l1 {
              0 => {
                let e37 = {
                  let l2 = i32::from(*base.add(8).cast::<u8>());

                  _rt::bool_lift(l2 as u8)
                };
                V37::BoolVal(e37)
              }
              1 => {
                let e37 = {
                  let l3 = *base.add(8).cast::<i64>();

                  l3
                };
                V37::IntVal(e37)
              }
              2 => {
                let e37 = {
                  let l4 = *base.add(8).cast::<f64>();

                  l4
                };
                V37::DecVal(e37)
              }
              3 => {
                let e37 = {
                  let l5 = *base.add(8).cast::<i32>();

                  _rt::char_lift(l5 as u32)
                };
                V37::CharVal(e37)
              }
              4 => {
                let e37 = {
                  let l6 = *base.add(8).cast::<*mut u8>();
                  let l7 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len8 = l7;
                  let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                  _rt::string_lift(bytes8)
                };
                V37::StrVal(e37)
              }
              5 => {
                let e37 = {
                  let l9 = *base.add(8).cast::<*mut u8>();
                  let l10 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len11 = l10;
                  let bytes11 = _rt::Vec::from_raw_parts(l9.cast(), len11, len11);

                  _rt::string_lift(bytes11)
                };
                V37::Sym(e37)
              }
              6 => {
                let e37 = {
                  let l12 = *base.add(8).cast::<*mut u8>();
                  let l13 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len14 = l13;
                  let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
                  let l15 = *base.add(8+2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l16 = *base.add(8+3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len17 = l16;
                  let bytes17 = _rt::Vec::from_raw_parts(l15.cast(), len17, len17);

                  (_rt::string_lift(bytes14), _rt::string_lift(bytes17))
                };
                V37::Qsym(e37)
              }
              7 => {
                let e37 = {
                  let l18 = *base.add(8).cast::<*mut u8>();
                  let l19 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len20 = l19;

                  _rt::Vec::from_raw_parts(l18.cast(), len20, len20)
                };
                V37::Tup(e37)
              }
              8 => {
                let e37 = {
                  let l21 = *base.add(8).cast::<*mut u8>();
                  let l22 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len23 = l22;

                  _rt::Vec::from_raw_parts(l21.cast(), len23, len23)
                };
                V37::Lst(e37)
              }
              9 => {
                let e37 = {
                  let l24 = *base.add(8).cast::<*mut u8>();
                  let l25 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base30 = l24;
                  let len30 = l25;
                  let mut result30 = _rt::Vec::with_capacity(len30);
                  for i in 0..len30 {
                    let base = base30.add(i * (3*::core::mem::size_of::<*const u8>()));
                    let e30 = {
                      let l26 = *base.add(0).cast::<*mut u8>();
                      let l27 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len28 = l27;
                      let bytes28 = _rt::Vec::from_raw_parts(l26.cast(), len28, len28);
                      let l29 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<i32>();

                      (_rt::string_lift(bytes28), l29 as u32)
                    };
                    result30.push(e30);
                  }
                  _rt::cabi_dealloc(base30, len30 * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());

                  result30
                };
                V37::Rec(e37)
              }
              n => {
                debug_assert_eq!(n, 10, "invalid enum discriminant");
                let e37 = {
                  let l31 = *base.add(8).cast::<*mut u8>();
                  let l32 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base36 = l31;
                  let len36 = l32;
                  let mut result36 = _rt::Vec::with_capacity(len36);
                  for i in 0..len36 {
                    let base = base36.add(i * (2*::core::mem::size_of::<*const u8>()));
                    let e36 = {
                      let l33 = *base.add(0).cast::<*mut u8>();
                      let l34 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      let len35 = l34;
                      let bytes35 = _rt::Vec::from_raw_parts(l33.cast(), len35, len35);

                      _rt::string_lift(bytes35)
                    };
                    result36.push(e36);
                  }
                  _rt::cabi_dealloc(base36, len36 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());

                  result36
                };
                V37::Flg(e37)
              }
            };

            v37
          };
          result38.push(e38);
        }
        _rt::cabi_dealloc(base38, len38 * (8+4*::core::mem::size_of::<*const u8>()), 8);
        let base41 = arg5;
        let len41 = arg6;
        let mut result41 = _rt::Vec::with_capacity(len41);
        for i in 0..len41 {
          let base = base41.add(i * 8);
          let e41 = {
            let l39 = *base.add(0).cast::<i32>();
            let l40 = *base.add(4).cast::<i32>();

            (l39 as u32, l40 as u32)
          };
          result41.push(e41);
        }
        _rt::cabi_dealloc(base41, len41 * 8, 4);
        T::expand(_rt::string_lift(bytes0), super::super::super::super::wavelet::meta::code::Tree{
          nodes: result38,
          root: arg4 as u32,
          spans: result41,
        })
      };
      let ptr43 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result42 {
        Ok(e) => { {
          *ptr43.add(0).cast::<u8>() = (0i32) as u8;
          let super::super::super::super::wavelet::meta::code::Tree{ nodes:nodes44, root:root44, spans:spans44, } = e;
          let vec58 = nodes44;
          let len58 = vec58.len();
          let layout58 = _rt::alloc::Layout::from_size_align(vec58.len() * (8+4*::core::mem::size_of::<*const u8>()), 8).unwrap();
          let (result58, _cleanup58) = wit_bindgen::rt::Cleanup::new(layout58);if let Some(cleanup) = _cleanup58 { cleanup.forget(); }
          for (i, e) in vec58.into_iter().enumerate() {
            let base = result58.add(i * (8+4*::core::mem::size_of::<*const u8>()));
            {
              use super::super::super::super::wavelet::meta::code::Node as V57;
              match e {
                V57::BoolVal(e) => {
                  *base.add(0).cast::<u8>() = (0i32) as u8;
                  *base.add(8).cast::<u8>() = (match e { true => 1, false => 0 }) as u8;
                },
                V57::IntVal(e) => {
                  *base.add(0).cast::<u8>() = (1i32) as u8;
                  *base.add(8).cast::<i64>() = _rt::as_i64(e);
                },
                V57::DecVal(e) => {
                  *base.add(0).cast::<u8>() = (2i32) as u8;
                  *base.add(8).cast::<f64>() = _rt::as_f64(e);
                },
                V57::CharVal(e) => {
                  *base.add(0).cast::<u8>() = (3i32) as u8;
                  *base.add(8).cast::<i32>() = _rt::as_i32(e);
                },
                V57::StrVal(e) => {
                  *base.add(0).cast::<u8>() = (4i32) as u8;
                  let vec45 = (e.into_bytes()).into_boxed_slice();
                  let ptr45 = vec45.as_ptr().cast::<u8>();
                  let len45 = vec45.len();
                  ::core::mem::forget(vec45);
                  *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len45;
                  *base.add(8).cast::<*mut u8>() = ptr45.cast_mut();
                },
                V57::Sym(e) => {
                  *base.add(0).cast::<u8>() = (5i32) as u8;
                  let vec46 = (e.into_bytes()).into_boxed_slice();
                  let ptr46 = vec46.as_ptr().cast::<u8>();
                  let len46 = vec46.len();
                  ::core::mem::forget(vec46);
                  *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len46;
                  *base.add(8).cast::<*mut u8>() = ptr46.cast_mut();
                },
                V57::Qsym(e) => {
                  *base.add(0).cast::<u8>() = (6i32) as u8;
                  let (t47_0, t47_1, ) = e;
                  let vec48 = (t47_0.into_bytes()).into_boxed_slice();
                  let ptr48 = vec48.as_ptr().cast::<u8>();
                  let len48 = vec48.len();
                  ::core::mem::forget(vec48);
                  *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len48;
                  *base.add(8).cast::<*mut u8>() = ptr48.cast_mut();
                  let vec49 = (t47_1.into_bytes()).into_boxed_slice();
                  let ptr49 = vec49.as_ptr().cast::<u8>();
                  let len49 = vec49.len();
                  ::core::mem::forget(vec49);
                  *base.add(8+3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len49;
                  *base.add(8+2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr49.cast_mut();
                },
                V57::Tup(e) => {
                  *base.add(0).cast::<u8>() = (7i32) as u8;
                  let vec50 = (e).into_boxed_slice();
                  let ptr50 = vec50.as_ptr().cast::<u8>();
                  let len50 = vec50.len();
                  ::core::mem::forget(vec50);
                  *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len50;
                  *base.add(8).cast::<*mut u8>() = ptr50.cast_mut();
                },
                V57::Lst(e) => {
                  *base.add(0).cast::<u8>() = (8i32) as u8;
                  let vec51 = (e).into_boxed_slice();
                  let ptr51 = vec51.as_ptr().cast::<u8>();
                  let len51 = vec51.len();
                  ::core::mem::forget(vec51);
                  *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len51;
                  *base.add(8).cast::<*mut u8>() = ptr51.cast_mut();
                },
                V57::Rec(e) => {
                  *base.add(0).cast::<u8>() = (9i32) as u8;
                  let vec54 = e;
                  let len54 = vec54.len();
                  let layout54 = _rt::alloc::Layout::from_size_align(vec54.len() * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
                  let (result54, _cleanup54) = wit_bindgen::rt::Cleanup::new(layout54);if let Some(cleanup) = _cleanup54 { cleanup.forget(); }
                  for (i, e) in vec54.into_iter().enumerate() {
                    let base = result54.add(i * (3*::core::mem::size_of::<*const u8>()));
                    {
                      let (t52_0, t52_1, ) = e;
                      let vec53 = (t52_0.into_bytes()).into_boxed_slice();
                      let ptr53 = vec53.as_ptr().cast::<u8>();
                      let len53 = vec53.len();
                      ::core::mem::forget(vec53);
                      *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len53;
                      *base.add(0).cast::<*mut u8>() = ptr53.cast_mut();
                      *base.add(2*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(t52_1);
                    }
                  }
                  *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len54;
                  *base.add(8).cast::<*mut u8>() = result54;
                },
                V57::Flg(e) => {
                  *base.add(0).cast::<u8>() = (10i32) as u8;
                  let vec56 = e;
                  let len56 = vec56.len();
                  let layout56 = _rt::alloc::Layout::from_size_align(vec56.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
                  let (result56, _cleanup56) = wit_bindgen::rt::Cleanup::new(layout56);if let Some(cleanup) = _cleanup56 { cleanup.forget(); }
                  for (i, e) in vec56.into_iter().enumerate() {
                    let base = result56.add(i * (2*::core::mem::size_of::<*const u8>()));
                    {
                      let vec55 = (e.into_bytes()).into_boxed_slice();
                      let ptr55 = vec55.as_ptr().cast::<u8>();
                      let len55 = vec55.len();
                      ::core::mem::forget(vec55);
                      *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len55;
                      *base.add(0).cast::<*mut u8>() = ptr55.cast_mut();
                    }
                  }
                  *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len56;
                  *base.add(8).cast::<*mut u8>() = result56;
                },
              }
            }
          }
          *ptr43.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len58;
          *ptr43.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result58;
          *ptr43.add(3*::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(root44);
          let vec60 = spans44;
          let len60 = vec60.len();
          let layout60 = _rt::alloc::Layout::from_size_align(vec60.len() * 8, 4).unwrap();
          let (result60, _cleanup60) = wit_bindgen::rt::Cleanup::new(layout60);if let Some(cleanup) = _cleanup60 { cleanup.forget(); }
          for (i, e) in vec60.into_iter().enumerate() {
            let base = result60.add(i * 8);
            {
              let (t59_0, t59_1, ) = e;
              *base.add(0).cast::<i32>() = _rt::as_i32(t59_0);
              *base.add(4).cast::<i32>() = _rt::as_i32(t59_1);
            }
          }
          *ptr43.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len60;
          *ptr43.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result60;
        } },
        Err(e) => { {
          *ptr43.add(0).cast::<u8>() = (1i32) as u8;
          let vec61 = (e.into_bytes()).into_boxed_slice();
          let ptr61 = vec61.as_ptr().cast::<u8>();
          let len61 = vec61.len();
          ::core::mem::forget(vec61);
          *ptr43.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len61;
          *ptr43.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr61.cast_mut();
        } },
      };ptr43
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_expand<T: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base28 = l1;
          let len28 = l2;
          for i in 0..len28 {
            let base = base28.add(i * (8+4*::core::mem::size_of::<*const u8>()));
            {
              let l3 = i32::from(*base.add(0).cast::<u8>());
              match l3 {
                0 => (),
                1 => (),
                2 => (),
                3 => (),
                4 => {
                  let l4 = *base.add(8).cast::<*mut u8>();
                  let l5 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l4, l5, 1);
                },
                5 => {
                  let l6 = *base.add(8).cast::<*mut u8>();
                  let l7 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l6, l7, 1);
                },
                6 => {
                  let l8 = *base.add(8).cast::<*mut u8>();
                  let l9 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l8, l9, 1);
                  let l10 = *base.add(8+2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l11 = *base.add(8+3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  _rt::cabi_dealloc(l10, l11, 1);
                },
                7 => {
                  let l12 = *base.add(8).cast::<*mut u8>();
                  let l13 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base14 = l12;
                  let len14 = l13;
                  _rt::cabi_dealloc(base14, len14 * 4, 4);
                },
                8 => {
                  let l15 = *base.add(8).cast::<*mut u8>();
                  let l16 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base17 = l15;
                  let len17 = l16;
                  _rt::cabi_dealloc(base17, len17 * 4, 4);
                },
                9 => {
                  let l18 = *base.add(8).cast::<*mut u8>();
                  let l19 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base22 = l18;
                  let len22 = l19;
                  for i in 0..len22 {
                    let base = base22.add(i * (3*::core::mem::size_of::<*const u8>()));
                    {
                      let l20 = *base.add(0).cast::<*mut u8>();
                      let l21 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l20, l21, 1);
                    }
                  }
                  _rt::cabi_dealloc(base22, len22 * (3*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
                },
                _ => {
                  let l23 = *base.add(8).cast::<*mut u8>();
                  let l24 = *base.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let base27 = l23;
                  let len27 = l24;
                  for i in 0..len27 {
                    let base = base27.add(i * (2*::core::mem::size_of::<*const u8>()));
                    {
                      let l25 = *base.add(0).cast::<*mut u8>();
                      let l26 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                      _rt::cabi_dealloc(l25, l26, 1);
                    }
                  }
                  _rt::cabi_dealloc(base27, len27 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
                },
              }
            }
          }
          _rt::cabi_dealloc(base28, len28 * (8+4*::core::mem::size_of::<*const u8>()), 8);
          let l29 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l30 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base31 = l29;
          let len31 = l30;
          _rt::cabi_dealloc(base31, len31 * 8, 4);
        },
        _ => {
          let l32 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l33 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l32, l33, 1);
        },
      }
    } }
    pub trait Guest {
      /// The macros this library publishes, as `(name, arity)` pairs. Arity is the
      /// number of argument forms the macro head consumes (TitleCase arity reading,
      /// §2.4).
      #[allow(async_fn_in_trait)]
      fn manifest() -> _rt::Vec::<(_rt::String,u32,)>;
      /// Expand one macro call. `name` is the macro's published name; `args` is the
      /// call's argument forms bundled into a single `tree` (its `root` is a `tup`
      /// whose elements are the arguments). Returns the rewritten form `tree`, or an
      /// error string the compiler surfaces as an expansion failure.
      #[allow(async_fn_in_trait)]
      fn expand(name: _rt::String,args: Tree,) -> Result<Tree,_rt::String>;
    }
    #[doc(hidden)]

    macro_rules! __export_wavelet_meta_macros_0_1_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "wavelet:meta/macros@0.1.0#manifest")]
        unsafe extern "C" fn export_manifest() -> *mut u8 {
          unsafe { $($path_to_types)*::_export_manifest_cabi::<$ty>() }
        }
        #[unsafe(export_name = "cabi_post_wavelet:meta/macros@0.1.0#manifest")]
        unsafe extern "C" fn _post_return_manifest(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_manifest::<$ty>(arg0) }
        }
        #[unsafe(export_name = "wavelet:meta/macros@0.1.0#expand")]
        unsafe extern "C" fn export_expand(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i32,arg5: *mut u8,arg6: usize,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_expand_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6) }
        }
        #[unsafe(export_name = "cabi_post_wavelet:meta/macros@0.1.0#expand")]
        unsafe extern "C" fn _post_return_expand(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_expand::<$ty>(arg0) }
        }
      };);
    }
    #[doc(hidden)]
    pub(crate) use __export_wavelet_meta_macros_0_1_0_cabi;

    #[cfg_attr(target_pointer_width="64", repr(align(8)))]
    #[cfg_attr(target_pointer_width="32", repr(align(4)))]
    struct _RetArea([::core::mem::MaybeUninit::<u8>; 6*::core::mem::size_of::<*const u8>()]);
    static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 6*::core::mem::size_of::<*const u8>()]);

  }

}
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub use alloc_crate::alloc;
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  pub unsafe fn char_lift(val: u32) -> char {
    if cfg!(debug_assertions) {
      core::char::from_u32(val).unwrap()
    } else {
      unsafe { core::char::from_u32_unchecked(val) }
    }
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  pub fn as_f64<T: AsF64>(t: T) -> f64 {
    t.as_f64()
  }

  pub trait AsF64 {
    fn as_f64(self) -> f64;
  }

  impl<'a, T: Copy + AsF64> AsF64 for &'a T {
    fn as_f64(self) -> f64 {
      (*self).as_f64()
    }
  }
  
  impl AsF64 for f64 {
    #[inline]
    fn as_f64(self) -> f64 {
      self as f64
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_macro_lib_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::wavelet::meta::macros::__export_wavelet_meta_macros_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::wavelet::meta::macros);
  )
}
#[doc(inline)]
pub(crate) use __export_macro_lib_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.43.0:wavelet:macro-guest@0.1.0:macro-lib:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 513] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x81\x03\x01A\x02\x01\
A\x05\x01B\x0e\x01y\x04\0\x07node-id\x03\0\0\x01o\x02ss\x01p\x01\x01o\x02s\x01\x01\
p\x04\x01ps\x01q\x0b\x08bool-val\x01\x7f\0\x07int-val\x01x\0\x07dec-val\x01u\0\x08\
char-val\x01t\0\x07str-val\x01s\0\x03sym\x01s\0\x04qsym\x01\x02\0\x03tup\x01\x03\
\0\x03lst\x01\x03\0\x03rec\x01\x05\0\x03flg\x01\x06\0\x04\0\x04node\x03\0\x07\x01\
p\x08\x01o\x02yy\x01p\x0a\x01r\x03\x05nodes\x09\x04root\x01\x05spans\x0b\x04\0\x04\
tree\x03\0\x0c\x03\0\x17wavelet:meta/code@0.1.0\x05\0\x02\x03\0\0\x04tree\x01B\x09\
\x02\x03\x02\x01\x01\x04\0\x04tree\x03\0\0\x01o\x02sy\x01p\x02\x01@\0\0\x03\x04\0\
\x08manifest\x01\x04\x01j\x01\x01\x01s\x01@\x02\x04names\x04args\x01\0\x05\x04\0\
\x06expand\x01\x06\x04\0\x19wavelet:meta/macros@0.1.0\x05\x02\x04\0#wavelet:macr\
o-guest/macro-lib@0.1.0\x04\0\x0b\x0f\x01\0\x09macro-lib\x03\0\0\0G\x09producers\
\x01\x0cprocessed-by\x02\x0dwit-component\x070.235.0\x10wit-bindgen-rust\x060.43\
.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

